"""add knowledge_base table

Revision ID: 0d6c1c7c75e7
Revises: f35671bd7a7b
Create Date: 2026-03-20 09:22:10.195035
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0d6c1c7c75e7'
down_revision: Union[str, None] = 'f35671bd7a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_content_trgm', 'knowledge_base', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kb_content_trgm', table_name='knowledge_base', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
