"""Initial schema - all tables

Revision ID: 2f149b9afa71
Revises: 
Create Date: 2026-03-17 10:47:36.964000
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f149b9afa71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_key', 'version', name='uq_prompt_key_version')
    )
    op.create_index('idx_prompt_active', 'prompt_versions', ['prompt_key'], unique=True, postgresql_where='is_active = TRUE')
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('digest_morning_time', sa.Time(), nullable=False),
    sa.Column('digest_evening_time', sa.Time(), nullable=False),
    sa.Column('memoir_prompt_time', sa.Time(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('frog_prompt_enabled', sa.Boolean(), nullable=False),
    sa.Column('chronometry_enabled', sa.Boolean(), nullable=False),
    sa.Column('chronometry_interval_min', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=False),
    sa.Column('work_end_time', sa.Time(), nullable=False),
    sa.Column('work_days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('focus_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('digest_sent_date', sa.Date(), nullable=True),
    sa.Column('memoir_asked_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diary_content_trgm', 'diary_entries', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_table('llm_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('prompt_key', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_content', sa.Text(), nullable=True),
    sa.Column('function_call', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_logs_key_time', 'llm_logs', ['prompt_key', 'created_at'], unique=False)
    op.create_table('llm_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('voice_transcript', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoir_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('value_tag', sa.Text(), nullable=True),
    sa.Column('period_type', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("period_type IN ('day', 'week', 'month', 'year')", name='ck_memoir_period_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_date', 'period_type', name='uq_memoir_user_date_period')
    )
    op.create_index('idx_memoir_content_trgm', 'memoir_entries', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_content_trgm', 'notes', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('task_ids_ordered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("category IN ('work', 'personal')", name='ck_projects_category'),
    sa.CheckConstraint("status IN ('active', 'paused', 'done')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_trips_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('is_frog', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_before_min', sa.Integer(), nullable=True),
    sa.Column('repeat_rule', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("category IN ('work', 'personal')", name='ck_tasks_category'),
    sa.CheckConstraint("priority IN ('high', 'medium', 'normal')", name='ck_tasks_priority'),
    sa.CheckConstraint("resolution IN ('completed', 'cancelled', 'deferred', 'expired')", name='ck_tasks_resolution'),
    sa.CheckConstraint("status IN ('open', 'done', 'cancelled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False, postgresql_where="status = 'open'")
    op.create_index('idx_tasks_frog', 'tasks', ['user_id'], unique=False, postgresql_where="is_frog = TRUE AND status = 'open'")
    op.create_index('idx_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_rule', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_pending', 'reminders', ['remind_at'], unique=False, postgresql_where='is_sent = FALSE')
    op.create_table('time_tracking_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.Column('matched_task_id', sa.UUID(), nullable=True),
    sa.Column('productivity_score', sa.Integer(), nullable=True),
    sa.Column('bot_reaction', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("category IN ('work', 'personal', 'rest', 'waste', 'focus')", name='ck_time_tracking_category'),
    sa.CheckConstraint('productivity_score BETWEEN 1 AND 5', name='ck_time_tracking_score'),
    sa.ForeignKeyConstraint(['matched_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_tracking_entries')
    op.drop_index('idx_reminders_pending', table_name='reminders', postgresql_where='is_sent = FALSE')
    op.drop_table('reminders')
    op.drop_index('idx_tasks_user_status', table_name='tasks')
    op.drop_index('idx_tasks_frog', table_name='tasks', postgresql_where="is_frog = TRUE AND status = 'open'")
    op.drop_index('idx_tasks_due_date', table_name='tasks', postgresql_where="status = 'open'")
    op.drop_table('tasks')
    op.drop_table('trips')
    op.drop_table('projects')
    op.drop_index('idx_notes_content_trgm', table_name='notes', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('notes')
    op.drop_index('idx_memoir_content_trgm', table_name='memoir_entries', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('memoir_entries')
    op.drop_table('llm_queue')
    op.drop_index('idx_llm_logs_key_time', table_name='llm_logs')
    op.drop_table('llm_logs')
    op.drop_index('idx_diary_content_trgm', table_name='diary_entries', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_table('diary_entries')
    op.drop_table('users')
    op.drop_index('idx_prompt_active', table_name='prompt_versions', postgresql_where='is_active = TRUE')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
