"""add_chronometry_last_asked_to_users

Revision ID: a0c4cff6709b
Revises: 028e00835b05
Create Date: 2026-03-19 12:01:43.005650
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0c4cff6709b'
down_revision: Union[str, None] = '028e00835b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chronometry_last_asked', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chronometry_last_asked')
    # ### end Alembic commands ###
