"""add_tasks_reminder_last_hour

Revision ID: f35671bd7a7b
Revises: a0c4cff6709b
Create Date: 2026-03-19 12:42:16.799440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35671bd7a7b'
down_revision: Union[str, None] = 'a0c4cff6709b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tasks_reminder_last_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tasks_reminder_last_hour')
    # ### end Alembic commands ###
